// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akgvthprfabfasuoqmrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZ3Z0aHByZmFiZmFzdW9xbXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzE2NjMsImV4cCI6MjA2OTUwNzY2M30.8N6flVzhL1XMXkfBvd09EmToOfLBQNzO7RbFcIRv_aU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});